---
- hosts: "baremetal*.ic.openstack.org:!disabled"
  gather_facts: true
  roles:
    - role: puppet
- hosts: "controller*.ic.openstack.org:!disabled"
  gather_facts: true
  roles:
    - role: puppet
      config: true
- hosts: "compute*.ic.openstack.org:!disabled"
  gather_facts: true
  roles:
    - role: puppet
      config: true
